version: "3"

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    ports:
     - "5173:5173"
    depends_on:
      - backend
