apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
     labels:
        app: postgres
    spec:
      containers:
       - name: postgres
         image: postgres:15
         ports:
          - containerPort: 5432
         env:
          - name: POSTGRES_DB
            value: testdb
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
        #  livenessProbe:
        #    httpGet:
        #     path: /
        #     port: 5432
        #    initialDelaySeconds: 30
        #    periodSeconds: 10
         resources:
           limits:
             memory: "512Mi"
             cpu: "500m"
           requests:
             memory: "256Mi"
             cpu: "256m"

---

apiVersion: v1
kind: Service 
metadata:
  name: postgres
  namespace: label
spec:
 selector:
   app: postgres
 ports:
  - port: 5432
    targetPort: 5432
